<a href="https://colab.research.google.com/github/vishalgit63/Data-Analysis/blob/main/House_price_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
df = pd.read_csv("House Price Prediction.csv")

In [6]:
df.head()

,id,number of bedrooms,living area,number of floors,Area of the basement,Built Year,Renovation Year,Number of schools nearby,Distance from the airport,Price
0,6762810145,5,3650,2.0,280,1921,0,2,58,2380000
1,6762810635,4,2920,1.5,1010,1909,0,2,51,1400000
2,6762810998,5,2910,1.5,0,1939,0,1,53,1200000
3,6762812605,4,3310,2.0,0,2001,0,3,76,838000
4,6762812919,3,2710,1.5,830,1929,0,1,51,805000

In [7]:
df.shape

(14620, 10)

In [8]:
df.columns

Index(['id', 'number of bedrooms', 'living area', 'number of floors',
       'Area of the basement', 'Built Year', 'Renovation Year',
       'Number of schools nearby', 'Distance from the airport', 'Price'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14620 entries, 0 to 14619
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         14620 non-null  int64
 1   number of bedrooms         14620 non-null  int64
 2   living area                14620 non-null  int64
 3   number of floors           14620 non-null  float64
 4   Area of the basement       14620 non-null  int64
 5   Built Year                 14620 non-null  int64
 6   Renovation Year            14620 non-null  int64
 7   Number of schools nearby   14620 non-null  int64
 8   Distance from the airport  14620 non-null  int64
 9   Price                      14620 non-null  int64
dtypes: float64(1), int64(9)
memory usage: 1.1 MB

In [22]:
import numpy as np
df
data = df.copy()
data

,id,number of bedrooms,living area,number of floors,Area of the basement,Built Year,Renovation Year,Number of schools nearby,Distance from the airport,Price
0,6762810145,5,3650,2.0,280,1921,0,2,58,2380000
1,6762810635,4,2920,1.5,1010,1909,0,2,51,1400000
2,6762810998,5,2910,1.5,0,1939,0,1,53,1200000
3,6762812605,4,3310,2.0,0,2001,0,3,76,838000
4,6762812919,3,2710,1.5,830,1929,0,1,51,805000
...,...,...,...,...,...,...,...,...,...,...
14615,6762830250,2,1556,1.0,0,1957,0,3,76,221700
14616,6762830339,3,1680,1.5,0,1968,0,3,59,219200
14617,6762830618,2,1070,1.0,0,1962,0,2,64,209000
14618,6762830709,4,1030,1.0,0,1955,0,3,54,205000
14619,6762831463,3,900,1.0,0,1969,2009,2,55,146000

In [23]:
data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
14615    False
14616    False
14617    False
14618    False
14619    False
Length: 14620, dtype: bool

In [26]:
data = data.drop(columns=['id','Renovation Year','Number of schools nearby', 'Distance from the airport'])

In [34]:
display(data.head())

,number of bedrooms,living area,number of floors,Area of the basement,Built Year,Price
0,5,3650,2.0,280,1921,2380000
1,4,2920,1.5,1010,1909,1400000
2,5,2910,1.5,0,1939,1200000
3,4,3310,2.0,0,2001,838000
4,3,2710,1.5,830,1929,805000

In [28]:
data.count()

number of bedrooms      14620
living area             14620
number of floors        14620
Area of the basement    14620
Built Year              14620
Price                   14620
dtype: int64

In [35]:
data = data.query("Price > 0 ")

In [36]:
data.shape

(14620, 6)

In [37]:
data

,number of bedrooms,living area,number of floors,Area of the basement,Built Year,Price
0,5,3650,2.0,280,1921,2380000
1,4,2920,1.5,1010,1909,1400000
2,5,2910,1.5,0,1939,1200000
3,4,3310,2.0,0,2001,838000
4,3,2710,1.5,830,1929,805000
...,...,...,...,...,...,...
14615,2,1556,1.0,0,1957,221700
14616,3,1680,1.5,0,1968,219200
14617,2,1070,1.0,0,1962,209000
14618,4,1030,1.0,0,1955,205000
14619,3,900,1.0,0,1969,146000

## Feature Label Seprations

* x = contains all columns except "Price" column
* y = contains only "Price" column

In [38]:
x = data.drop(columns=['Price'])

In [39]:
y = data['Price']

# Train test Spiliting

In [40]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [43]:
data.shape

(14620, 6)

In [45]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((11696, 5), (2924, 5), (11696,), (2924,))

In [ ]:
-